services:
  spring-app:
    image: avalanche-homework:latest
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql-db
      POSTGRES_HOST: postgres-db
    depends_on:
      postgres-db:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: vessels_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: starships_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5